program: lynx/agents/dqn/trial.py
project: snake-sweep
method: bayes
metric:
  goal: maximize 
  name: train/episode_return/mean 
parameters:
  rollout_length:
    distribution: int_uniform
    min: 10
    max: 11
  updates_per_epoch:
    distribution: int_uniform
    min: 10
    max: 50
  batch_size:
    distribution: int_uniform
    min: 32
    max: 8192
  tau:
    distribution: uniform
    min: 1e-8
    max: 1e-3
  learning_rate:
    distribution: uniform
    min: 1e-7
    max: 1e-3
  training_epsilon:
    distribution: uniform
    min: 0.01
    max: 0.3
  huber_loss_parameter:
    distribution: uniform 
    min: 0.0
    max: 1.0
early_terminate:
  type: hyperband
  min_iter: 1
  s: 2 # Number of brackets
  eta: 10 # Only 1/eta runs survive at each halving stage (lower more aggressive pruning)
  strict: true # follot paper implementation (more aggressive)
command:
  - ${interpreter}
  - ${program}
  - ${args_json_file}
