partition: bigbatch
time_limit: "72:00:00"
job_name: snake-exp
remote_project_dir: /home-mscluster/tbester/lynx
experiment_script: lynx/agents/dqn/exp.py
seed_count: 99
concurrency_limit: 5
agents_per_node: 1
node_count: 1
