defaults:  
  - _self_  
  # - run_type: train # What to do with all this config
  - environment: snake 
  - network: dqn
  - train: dqn 
  # - sweep: dqn
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  searchpath: 
    - pkg://lynx/configs
  output_subdir: null  
  run:  
    dir: .





