defaults:  
  - _self_  
  - environment: puzzle 
  - network: dqn
  - train: dqn 
  - logger: wandb
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  searchpath: 
    - pkg://lynx/configs
  output_subdir: null  
  run:  
    dir: .





